version: "3.4"
services:
  uuid-api:
    container_name: uuid-api
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - ./Uuid:/api
    working_dir: /api   
    command: "dotnet run"
    ports:
      - "8001:8081"
  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command:
      [
        "dotnet",
        "test",
        "../test/Uuid.Tests.csproj"
      ]